// GENERATED by scripts/generate-types.mjs from openapi.json (Broadcastwell API 1.0.0).
// Do not edit by hand. Run `npm run generate` in packages/api after updating openapi.json.

// ---------- Component schemas ----------

/** ChatGPT, Claude, Perplexity, Google AI Overviews, Google AI Mode. */
export type EngineId = "chatgpt" | "claude" | "perplexity" | "google_aio" | "google_ai_mode";

export interface Rate {
  pct: number;
  low: number;
  high: number;
  interval: string;
  base: string;
}

export interface Pagination {
  limit: number;
  next_cursor: string | null;
  total: number;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Problem {
  type: string;
  title: string;
  status: number;
  code: string;
  detail: string;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Pass {
  pass_id?: string;
  kind?: "scheduled" | "adaptive" | "monitor";
  scheduled?: boolean;
  started_at?: string;
  completed_at?: string;
  observed?: number;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Run {
  run_id: string;
  kind: string;
  status: string;
  method_version?: string;
  immutable?: boolean;
  question_count?: number;
  engines?: unknown[];
  passes?: Array<Pass>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Counted {
  observed?: number;
  scored?: number;
  excluded?: number;
  named?: number;
  named_rate?: Rate;
  own_domain_cited?: number;
  cited_rate?: Rate;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface RunSummary {
  run_id?: string;
  method_version?: string;
  scheduled?: Counted;
  adaptive?: Counted | null;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Question {
  question_id?: number;
  question_text?: string;
  question_type?: string;
  named?: number;
  scored?: number;
  named_rate?: Rate;
  per_engine?: Record<string, unknown>;
  competitors_named?: unknown[];
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Receipt {
  receipt_id?: string;
  pass_id?: string;
  pass_kind?: string;
  question_id?: number;
  engine?: EngineId;
  engine_label?: string;
  verdict?: "named" | "not_named" | "excluded";
  competitors_found?: Array<string>;
  cited_urls?: Array<string>;
  answer_text?: string;
  observed_at?: string;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface DisplacementQuestion {
  question_id?: number;
  scored?: number;
  client_named?: number;
  client_absent?: number;
  competitors?: Array<{
    name?: string;
    checked_in?: number;
    named?: number;
    named_instead?: number;
    status?: "named" | "checked_not_found" | "not_checked";
    /** Version 1 changes only by addition: extra fields may appear. */
    [key: string]: unknown;
  }>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Source {
  url?: string;
  domain?: string;
  own_domain?: boolean;
  times_cited?: number;
  engines?: unknown[];
  question_ids?: Array<number>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Fix {
  fix_id?: string;
  run_id?: string | null;
  question_ids?: Array<number>;
  observed_source?: string;
  change_to_test?: string;
  status?: string;
  shipped_on?: string | null;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface HistoryScope {
  scope?: string;
  key?: string;
  label?: string;
  points?: unknown[];
  steps?: unknown[];
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Alert {
  alert_id?: string;
  scope?: string;
  key?: string;
  direction?: "up" | "down";
  statement?: string;
  from?: Record<string, unknown>;
  to?: Record<string, unknown>;
  links?: Record<string, unknown>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface ProofResult {
  experiment_id?: string;
  name?: string;
  version?: number;
  locked_at?: string | null;
  state?: string;
  target?: Record<string, unknown>;
  control?: Record<string, unknown>;
  controlled_lift?: {
    points?: number;
    low?: number;
    high?: number;
    /** Version 1 changes only by addition: extra fields may appear. */
    [key: string]: unknown;
  };
  verdict?: "Lift shown" | "Gain on target questions, not separable from drift" | "No gain observed" | null;
  remeasure?: Record<string, unknown>;
  limit?: string;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Method {
  measurement_method?: string;
  proof_addendum?: string;
  engines?: unknown[];
  definitions?: Record<string, unknown>;
  what_the_numbers_do_not_prove?: Array<string>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

export interface Event {
  id: string;
  type: "run.completed" | "alert.fired" | "fix.updated" | "proof.updated";
  api_version: string;
  created_at: string;
  account_id: string;
  data: Record<string, unknown>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

// ---------- Parameters and responses per route ----------

/** Options accepted by every method. */
export interface RequestOptions {
  /** Send If-None-Match. A 304 resolves to a NotModified object instead of the body. */
  ifNoneMatch?: string;
  /** Abort the request. */
  signal?: AbortSignal;
}

/** Returned instead of the body when If-None-Match matched (HTTP 304). */
export interface NotModified {
  notModified: true;
  etag: string | null;
}

/** Parameters for getMe: GET /me */
export type GetMeParams = Record<string, never>;

/** Response body for getMe. */
export interface GetMeResponse {
  sample?: boolean;
  data: Record<string, unknown>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getMethod: GET /method */
export type GetMethodParams = Record<string, never>;

/** Response body for getMethod. */
export interface GetMethodResponse {
  sample?: boolean;
  data: Method;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getAccount: GET /accounts/{account} */
export interface GetAccountParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
}

/** Response body for getAccount. */
export interface GetAccountResponse {
  sample?: boolean;
  data: Record<string, unknown>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listRuns: GET /accounts/{account}/runs */
export interface ListRunsParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listRuns. */
export interface ListRunsResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<Run>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getRun: GET /accounts/{account}/runs/{run} */
export interface GetRunParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
}

/** Response body for getRun. */
export interface GetRunResponse {
  sample?: boolean;
  data: Run;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getRunSummary: GET /accounts/{account}/runs/{run}/summary */
export interface GetRunSummaryParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
}

/** Response body for getRunSummary. */
export interface GetRunSummaryResponse {
  sample?: boolean;
  data: RunSummary;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listQuestions: GET /accounts/{account}/runs/{run}/questions */
export interface ListQuestionsParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listQuestions. */
export interface ListQuestionsResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<Question>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getQuestion: GET /accounts/{account}/runs/{run}/questions/{question} */
export interface GetQuestionParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  question: number;
}

/** Response body for getQuestion. */
export interface GetQuestionResponse {
  sample?: boolean;
  data: Question;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listReceipts: GET /accounts/{account}/runs/{run}/receipts */
export interface ListReceiptsParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  question_id?: number;
  engine?: EngineId;
  pass_id?: string;
  verdict?: "named" | "not_named" | "excluded";
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listReceipts. */
export interface ListReceiptsResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<Receipt>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getReceipt: GET /accounts/{account}/runs/{run}/receipts/{receipt} */
export interface GetReceiptParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  receipt: string;
}

/** Response body for getReceipt. */
export interface GetReceiptResponse {
  sample?: boolean;
  data: Receipt;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listDisplacement: GET /accounts/{account}/runs/{run}/displacement */
export interface ListDisplacementParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listDisplacement. */
export interface ListDisplacementResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<DisplacementQuestion>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listSources: GET /accounts/{account}/runs/{run}/sources */
export interface ListSourcesParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listSources. */
export interface ListSourcesResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<Source>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listRunFixes: GET /accounts/{account}/runs/{run}/fixes */
export interface ListRunFixesParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
}

/** Response body for listRunFixes. */
export interface ListRunFixesResponse {
  sample?: boolean;
  data: Array<Fix>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for compareRuns: GET /accounts/{account}/runs/{run}/compare/{other} */
export interface CompareRunsParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** A run id from the runs list. */
  run: string;
  /** The second run id. */
  other: string;
}

/** Response body for compareRuns. */
export interface CompareRunsResponse {
  sample?: boolean;
  data: Record<string, unknown>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listFixes: GET /accounts/{account}/fixes */
export interface ListFixesParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
}

/** Response body for listFixes. */
export interface ListFixesResponse {
  sample?: boolean;
  data: Array<Fix>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getHistory: GET /accounts/{account}/history */
export interface GetHistoryParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  scope?: "account" | "engine" | "question_type";
}

/** Response body for getHistory. */
export interface GetHistoryResponse {
  sample?: boolean;
  data: Array<HistoryScope>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listAlerts: GET /accounts/{account}/alerts */
export interface ListAlertsParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  /** Items per page, 1 to 100. Default 25. */
  limit?: number;
  /** The next_cursor from the previous page. */
  cursor?: string;
}

/** Response body for listAlerts. */
export interface ListAlertsResponse {
  /** Present and true on every sample response. */
  sample?: boolean;
  data: Array<Alert>;
  pagination: Pagination;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for listProof: GET /accounts/{account}/proof */
export interface ListProofParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
}

/** Response body for listProof. */
export interface ListProofResponse {
  sample?: boolean;
  data: Array<ProofResult>;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Parameters for getProof: GET /accounts/{account}/proof/{experiment} */
export interface GetProofParams {
  /** me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404. Defaults to the client's account (me, or sample with the demo key). */
  account?: string;
  experiment: string;
}

/** Response body for getProof. */
export interface GetProofResponse {
  sample?: boolean;
  data: ProofResult;
  /** Version 1 changes only by addition: extra fields may appear. */
  [key: string]: unknown;
}

/** Method names whose responses page with pagination.next_cursor. */
export type PagedMethod = "listRuns" | "listQuestions" | "listReceipts" | "listDisplacement" | "listSources" | "listAlerts";

/** The item type each paged method yields from paginate(). */
export interface PagedItem {
  listRuns: ListRunsResponse['data'][number];
  listQuestions: ListQuestionsResponse['data'][number];
  listReceipts: ListReceiptsResponse['data'][number];
  listDisplacement: ListDisplacementResponse['data'][number];
  listSources: ListSourcesResponse['data'][number];
  listAlerts: ListAlertsResponse['data'][number];
}

/** Parameters per method name. */
export interface MethodParams {
  getMe: GetMeParams;
  getMethod: GetMethodParams;
  getAccount: GetAccountParams;
  listRuns: ListRunsParams;
  getRun: GetRunParams;
  getRunSummary: GetRunSummaryParams;
  listQuestions: ListQuestionsParams;
  getQuestion: GetQuestionParams;
  listReceipts: ListReceiptsParams;
  getReceipt: GetReceiptParams;
  listDisplacement: ListDisplacementParams;
  listSources: ListSourcesParams;
  listRunFixes: ListRunFixesParams;
  compareRuns: CompareRunsParams;
  listFixes: ListFixesParams;
  getHistory: GetHistoryParams;
  listAlerts: ListAlertsParams;
  listProof: ListProofParams;
  getProof: GetProofParams;
}

// ---------- Client ----------

export interface BroadcastwellClient {
  /** The key you are using. Who the key belongs to and which accounts it reads. (GET /me) */
  getMe(params?: GetMeParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetMeResponse>;
  getMe(params: GetMeParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetMeResponse | NotModified>;
  /** Method, definitions and limits. The method version, every definition, the five engines, the proof rules and what the numbers do not prove. No key needed. (GET /method) */
  getMethod(params?: GetMethodParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetMethodResponse>;
  getMethod(params: GetMethodParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetMethodResponse | NotModified>;
  /** One account (GET /accounts/{account}) */
  getAccount(params?: GetAccountParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetAccountResponse>;
  getAccount(params: GetAccountParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetAccountResponse | NotModified>;
  /** Runs. Every measurement the account holds, newest first, with its passes. Scheduled passes carry the figures. Adaptive passes are labelled. (GET /accounts/{account}/runs) */
  listRuns(params?: ListRunsParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListRunsResponse>;
  listRuns(params: ListRunsParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListRunsResponse | NotModified>;
  /** One run (GET /accounts/{account}/runs/{run}) */
  getRun(params: GetRunParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetRunResponse>;
  getRun(params: GetRunParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetRunResponse | NotModified>;
  /** Run summary. Named and own domain cited rates on scheduled passes, overall, per engine and per question type. Adaptive answers are reported separately. (GET /accounts/{account}/runs/{run}/summary) */
  getRunSummary(params: GetRunSummaryParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetRunSummaryResponse>;
  getRunSummary(params: GetRunSummaryParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetRunSummaryResponse | NotModified>;
  /** Questions (GET /accounts/{account}/runs/{run}/questions) */
  listQuestions(params: ListQuestionsParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListQuestionsResponse>;
  listQuestions(params: ListQuestionsParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListQuestionsResponse | NotModified>;
  /** One question. Counts per engine, competitors named and who was named instead. (GET /accounts/{account}/runs/{run}/questions/{question}) */
  getQuestion(params: GetQuestionParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetQuestionResponse>;
  getQuestion(params: GetQuestionParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetQuestionResponse | NotModified>;
  /** Receipts. Observed answers with their verdict and every cited address. (GET /accounts/{account}/runs/{run}/receipts) */
  listReceipts(params: ListReceiptsParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListReceiptsResponse>;
  listReceipts(params: ListReceiptsParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListReceiptsResponse | NotModified>;
  /** One receipt (GET /accounts/{account}/runs/{run}/receipts/{receipt}) */
  getReceipt(params: GetReceiptParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetReceiptResponse>;
  getReceipt(params: GetReceiptParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetReceiptResponse | NotModified>;
  /** Named instead. Per question, who was named in answers that did not name the client, including competitors checked and not found. (GET /accounts/{account}/runs/{run}/displacement) */
  listDisplacement(params: ListDisplacementParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListDisplacementResponse>;
  listDisplacement(params: ListDisplacementParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListDisplacementResponse | NotModified>;
  /** Sources. Every page cited in scheduled answers, with times cited, engines and questions. (GET /accounts/{account}/runs/{run}/sources) */
  listSources(params: ListSourcesParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListSourcesResponse>;
  listSources(params: ListSourcesParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListSourcesResponse | NotModified>;
  /** Fixes for a run (GET /accounts/{account}/runs/{run}/fixes) */
  listRunFixes(params: ListRunFixesParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListRunFixesResponse>;
  listRunFixes(params: ListRunFixesParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListRunFixesResponse | NotModified>;
  /** Compare two runs. Named rates on the questions and engines both runs measured. A change is called only where the intervals separate, and never across method versions. (GET /accounts/{account}/runs/{run}/compare/{other}) */
  compareRuns(params: CompareRunsParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<CompareRunsResponse>;
  compareRuns(params: CompareRunsParams, options: RequestOptions & { ifNoneMatch: string }): Promise<CompareRunsResponse | NotModified>;
  /** Fixes (GET /accounts/{account}/fixes) */
  listFixes(params?: ListFixesParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListFixesResponse>;
  listFixes(params: ListFixesParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListFixesResponse | NotModified>;
  /** History. One point per scheduled run with its interval, for the account, each engine and each question type. Moved is printed only where intervals separate. Method breaks are marked. (GET /accounts/{account}/history) */
  getHistory(params?: GetHistoryParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetHistoryResponse>;
  getHistory(params: GetHistoryParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetHistoryResponse | NotModified>;
  /** Alerts. Movements between consecutive comparable scheduled runs where the two intervals separate, in either direction. (GET /accounts/{account}/alerts) */
  listAlerts(params?: ListAlertsParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListAlertsResponse>;
  listAlerts(params: ListAlertsParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListAlertsResponse | NotModified>;
  /** Proof. Controlled lift experiments with the four counts, intervals, the lift in points and the fixed verdict. (GET /accounts/{account}/proof) */
  listProof(params?: ListProofParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<ListProofResponse>;
  listProof(params: ListProofParams, options: RequestOptions & { ifNoneMatch: string }): Promise<ListProofResponse | NotModified>;
  /** One experiment (GET /accounts/{account}/proof/{experiment}) */
  getProof(params: GetProofParams, options?: RequestOptions & { ifNoneMatch?: undefined }): Promise<GetProofResponse>;
  getProof(params: GetProofParams, options: RequestOptions & { ifNoneMatch: string }): Promise<GetProofResponse | NotModified>;
  /** Follow pagination.next_cursor and yield every item. */
  paginate<K extends PagedMethod>(method: K, params?: MethodParams[K], options?: { signal?: AbortSignal; maxItems?: number }): AsyncGenerator<PagedItem[K], void, unknown>;
  /** Low level: call any route by name. */
  request<K extends keyof MethodParams>(method: K, params?: MethodParams[K], options?: RequestOptions): Promise<unknown>;
  /** The account used when a call leaves account out. */
  readonly account: string;
  readonly baseUrl: string;
}

export interface ClientOptions {
  /** An account key (bwp_ followed by 64 hex characters) or the public demo key. */
  apiKey: string;
  /** Defaults to https://app.broadcastwell.com/api/v1 */
  baseUrl?: string;
  /** A fetch implementation. Defaults to globalThis.fetch (Node 18 and later, browsers, workers). */
  fetch?: (input: string, init?: Record<string, unknown>) => Promise<unknown>;
  /** Sent as User-Agent where the runtime allows it. */
  userAgent?: string;
  /** Account used when a call leaves account out. Defaults to sample for the demo key and me otherwise. */
  account?: string;
  /** Retry once after a 429, waiting Retry-After seconds. Default true. */
  retryOn429?: boolean;
  /** Longest Retry-After the single retry will wait, in seconds. Default 60. */
  maxRetryAfterSeconds?: number;
  /** Replaceable sleep, used for the 429 retry. */
  sleep?: (ms: number) => Promise<void>;
}

export interface ResponseMeta {
  status: number;
  url: string;
  etag: string | null;
  rateLimit: { limit: number | null; remaining: number | null; reset: number | null };
}

export declare function createClient(options: ClientOptions): BroadcastwellClient;

/** Status, ETag and RateLimit headers of the response a body came from. */
export declare function getResponseMeta(body: object): ResponseMeta | undefined;

/** True when a call made with ifNoneMatch came back 304 Not Modified. */
export declare function isNotModified(value: unknown): value is NotModified;

export declare class BroadcastwellApiError extends Error {
  readonly name: 'BroadcastwellApiError';
  /** HTTP status, or 0 when the request never got a response. */
  readonly status: number;
  /** Problem code: unauthorized, key_revoked, not_found, run_not_delivered, rate_limited and so on. */
  readonly code: string;
  readonly detail: string;
  readonly title: string;
  readonly type: string;
  /** Seconds from the Retry-After header, when present. */
  readonly retryAfter: number | null;
  readonly url: string;
  /** The parsed problem body, when there was one. */
  readonly body: unknown;
}

export interface RouteParam {
  name: string;
  type: 'string' | 'integer';
  description: string;
  enum?: Array<string | number>;
  minimum?: number;
  maximum?: number;
  maxLength?: number;
  pattern?: string;
  default?: unknown;
}

export interface Route {
  name: keyof MethodParams;
  method: 'GET';
  path: string;
  summary: string;
  description: string;
  tag: string;
  auth: boolean;
  pathParams: RouteParam[];
  queryParams: RouteParam[];
  paged: boolean;
  returns: 'object' | 'array' | 'page';
}

/** Every route keyed by method name. The one place that knows the routes. */
export declare const routes: { readonly [K in keyof MethodParams]: Route };
export declare function buildPath(route: Route | keyof MethodParams, params?: Record<string, unknown>): string;
export declare function buildQuery(route: Route | keyof MethodParams, params?: Record<string, unknown>): string;

export declare const API_VERSION: string;
export declare const DEFAULT_BASE_URL: string;
/** The public demo key. It reads only the fictional Kalvenor sample account. */
export declare const DEMO_KEY: 'bwp_demo_kalvenor_sample';
/** Account id of the fictional Kalvenor sample. */
export declare const SAMPLE_ACCOUNT: 'sample';
export declare const ENGINE_IDS: readonly EngineId[];
/** Engine labels, exactly as the product names them. */
export declare const ENGINES: Readonly<Record<EngineId, string>>;
/** Webhook event types, including webhook.test sent by Send test event. */
export declare const EVENT_TYPES: readonly ['run.completed', 'alert.fired', 'fix.updated', 'proof.updated', 'webhook.test'];
export type EventType = (typeof EVENT_TYPES)[number];
/** Receivers reject a signature timestamp further than this from their clock (300). */
export declare const SIGNATURE_TOLERANCE_SECONDS: number;
export declare const WEBHOOK_HEADERS: Readonly<{
  signature: 'Broadcastwell-Signature';
  event: 'Broadcastwell-Event';
  eventId: 'Broadcastwell-Event-Id';
  delivery: 'Broadcastwell-Delivery';
}>;

export interface WebhookEnvelope extends Omit<Event, 'type'> {
  type: EventType;
}

export interface VerifyResult {
  valid: boolean;
  /** Why verification failed: missing_header, malformed_header, stale_timestamp, signature_mismatch, missing_secret. */
  reason?: string;
  /** The t value from the header, in unix seconds. */
  timestamp?: number;
}

/**
 * Verify a Broadcastwell-Signature header against the raw request body.
 * HMAC SHA-256 of "<t>.<raw body>" with the signing secret, compared in constant time.
 * Uses WebCrypto, so it runs in Node 18 and later, browsers and workers.
 */
export declare function verifyWebhookSignature(
  secret: string,
  header: string | null | undefined,
  rawBody: string | Uint8Array | ArrayBuffer,
  options?: { toleranceSeconds?: number; now?: number },
): Promise<VerifyResult>;

/** Build a Broadcastwell-Signature header value. Useful for testing a receiver. */
export declare function signWebhookPayload(
  secret: string,
  rawBody: string | Uint8Array | ArrayBuffer,
  timestamp?: number,
): Promise<string>;

export declare function parseSignatureHeader(header: string | null | undefined): { t: number; v1: string[] } | null;
