#!/usr/bin/env node
// Builds the CommonJS and script tag copies of the client from the ESM source.
// No bundler: the source is three small ES modules with a known shape, so the
// build strips import lines and export keywords and adds the right wrapper.
//
//   dist/index.cjs                 require('@broadcastwell/api')
//   dist/broadcastwell.global.js   a plain script that defines a global Broadcastwell
//                                  (browsers and Google Apps Script)
//
//   node scripts/build.mjs          write the files
//   node scripts/build.mjs --check  fail if the committed files are stale

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..');
const src = (f) => readFile(join(pkgDir, 'src', f), 'utf8');

const pkg = JSON.parse(await readFile(join(pkgDir, 'package.json'), 'utf8'));
const [constants, routesSrc, index] = await Promise.all([
  src('constants.mjs'),
  src('routes.mjs'),
  src('index.mjs'),
]);

// The export list at the bottom of index.mjs is the public surface.
const exportBlock = index.match(/\nexport \{([\s\S]*?)\};\s*$/);
if (!exportBlock) throw new Error('index.mjs must end with an export { ... } block');
const names = exportBlock[1]
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

function strip(code) {
  return code
    .replace(/^import[\s\S]*?from\s+'[^']+';\s*$/gm, '')
    .replace(/\nexport \{[\s\S]*?\};\s*$/, '\n')
    .replace(/^export (const|function|async function|class) /gm, '$1 ');
}

const body = [strip(constants), strip(routesSrc), strip(index)].join('\n');
const header = `// ${pkg.name} ${pkg.version}. GENERATED by scripts/build.mjs from src/. Do not edit by hand.\n`;

const cjs = `${header}'use strict';\n${body}\nmodule.exports = { ${names.join(', ')} };\n`;

// Script builds cannot use dynamic import. The Node 18 WebCrypto fallback is not
// needed there because browsers and Apps Script callers bring their own crypto.
const globalBody = body.replace(
  /const mod = await import\('node:crypto'\);\s*return mod\.webcrypto\.subtle;/,
  "throw new Error('WebCrypto is not available in this runtime');",
);
const globalJs = `${header}var Broadcastwell = (function () {\n  'use strict';\n${globalBody}\n  return { ${names.join(', ')} };\n})();\nif (typeof module !== 'undefined' && module.exports) module.exports = Broadcastwell;\n`;

const outputs = {
  [join(pkgDir, 'dist', 'index.cjs')]: cjs,
  [join(pkgDir, 'dist', 'broadcastwell.global.js')]: globalJs,
};

if (process.argv.includes('--check')) {
  let stale = false;
  for (const [path, content] of Object.entries(outputs)) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== content) {
      console.error(`Stale: ${path}. Run npm run build.`);
      stale = true;
    }
  }
  process.exit(stale ? 1 : 0);
}

await mkdir(join(pkgDir, 'dist'), { recursive: true });
for (const [path, content] of Object.entries(outputs)) {
  await writeFile(path, content, 'utf8');
  console.log(`Wrote ${path}`);
}
