#!/usr/bin/env node
// Builds the Apps Script files for the Looker Studio connector. No dependencies.
//
//   node scripts/build.mjs          writes dist/Code.js and dist/appsscript.json
//   node scripts/build.mjs --check  fails when dist/ is out of date
//
// dist/Code.js is one file you can paste into the Apps Script editor or push with clasp.
// It starts with a BroadcastwellRoutes block generated from packages/api:
//   - src/routes.mjs      (API_VERSION, DEFAULT_BASE_URL, ENGINE_IDS, routes), whole
//   - src/constants.mjs   (DEMO_KEY, SAMPLE_ACCOUNT, ENGINES), whole
//   - src/index.mjs       resolveRoute, buildPath and buildQuery, copied verbatim
// so the routes live in one place. The Promise based createClient() is left out on
// purpose: Looker Studio needs getData() to return rows synchronously. See src/Api.js.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const API = join(ROOT, '..', 'packages', 'api', 'src');
const SOURCES = ['Schema.js', 'Mapping.js', 'Api.js', 'Code.js'];
const EXPORTS = [
  'API_VERSION',
  'DEFAULT_BASE_URL',
  'ENGINE_IDS',
  'routes',
  'DEMO_KEY',
  'SAMPLE_ACCOUNT',
  'ENGINES',
  'resolveRoute',
  'buildPath',
  'buildQuery',
];

function stripExports(source) {
  return source.replace(/^export\s+(const|function|let|var)\s/gm, '$1 ');
}

// Copies resolveRoute, buildPath and buildQuery out of packages/api/src/index.mjs.
function pathHelpers(index) {
  const start = index.indexOf('function resolveRoute(');
  const endMarker = index.indexOf('// Response metadata');
  if (start < 0 || endMarker < 0 || endMarker < start) {
    throw new Error('packages/api/src/index.mjs changed shape: could not find resolveRoute ... buildQuery.');
  }
  const end = index.lastIndexOf('// ----', endMarker);
  const slice = index.slice(start, end).trim();
  for (const name of ['function resolveRoute(', 'function buildPath(', 'function buildQuery(']) {
    if (!slice.includes(name)) throw new Error('Missing ' + name + ' in the copied helpers.');
  }
  if (/\basync\b|\bawait\b|\bimport\s*\(|\bfetch\s*\(/.test(slice)) {
    throw new Error('The copied path helpers are no longer synchronous. Review scripts/build.mjs.');
  }
  return slice;
}

export async function routesBlock() {
  const [routes, constants, index, pkg] = await Promise.all([
    readFile(join(API, 'routes.mjs'), 'utf8'),
    readFile(join(API, 'constants.mjs'), 'utf8'),
    readFile(join(API, 'index.mjs'), 'utf8'),
    readFile(join(API, '..', 'package.json'), 'utf8'),
  ]);
  const version = JSON.parse(pkg).version;
  return [
    '// ---------------------------------------------------------------------------',
    '// BroadcastwellRoutes: GENERATED from packages/api ' + version + ' by looker-studio/scripts/build.mjs.',
    '// Do not edit here. Change packages/api and rebuild.',
    '// ---------------------------------------------------------------------------',
    'var BroadcastwellRoutes = (function () {',
    "  'use strict';",
    stripExports(constants).trim(),
    '',
    stripExports(routes).trim(),
    '',
    pathHelpers(index),
    '',
    '  return { ' + EXPORTS.join(', ') + ' };',
    '})();',
    '',
  ].join('\n');
}

export async function bundle() {
  const parts = [
    '// Broadcastwell Looker Studio connector. GENERATED by looker-studio/scripts/build.mjs',
    '// from looker-studio/src and packages/api/src. Edit those files, not this one.',
    '// MIT licence. https://github.com/Broadcastwell/bw-connectors',
    '',
    await routesBlock(),
  ];
  for (const file of SOURCES) {
    parts.push('// ===== src/' + file + ' =====');
    parts.push((await readFile(join(ROOT, 'src', file), 'utf8')).trim());
    parts.push('');
  }
  return parts.join('\n');
}

export async function manifest() {
  return readFile(join(ROOT, 'src', 'appsscript.json'), 'utf8');
}

async function main() {
  const check = process.argv.includes('--check');
  const outputs = {
    'Code.js': await bundle(),
    'appsscript.json': await manifest(),
  };
  const dist = join(ROOT, 'dist');
  if (check) {
    let stale = 0;
    for (const [name, content] of Object.entries(outputs)) {
      const current = await readFile(join(dist, name), 'utf8').catch(() => '');
      if (current !== content) {
        stale++;
        console.error('dist/' + name + ' is out of date. Run node scripts/build.mjs.');
      }
    }
    if (stale) process.exit(1);
    console.log('dist/ is up to date.');
    return;
  }
  await mkdir(dist, { recursive: true });
  for (const [name, content] of Object.entries(outputs)) {
    await writeFile(join(dist, name), content);
    console.log('wrote dist/' + name + ' (' + content.length + ' characters)');
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}
