#!/usr/bin/env node
// Copies the routes table and constants from @broadcastwell/api (packages/api) into
// nodes/shared/broadcastwell.generated.ts.
//
// Why a copy: verified n8n community nodes must have no runtime dependencies, so this
// package cannot depend on @broadcastwell/api. The API package stays the single source
// of routes (itself generated from the OpenAPI document); this script vendors its data
// into TypeScript at build time, and CI fails if the copy is stale.
//
//   node scripts/sync-routes.mjs          write the file
//   node scripts/sync-routes.mjs --check  fail if the committed file is stale
//
// Outside this repository (packages/api missing) the committed copy is used as is.

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..');
const apiSrc = join(pkgDir, '..', 'api', 'src');
const target = join(pkgDir, 'nodes', 'shared', 'broadcastwell.generated.ts');

if (!existsSync(join(apiSrc, 'routes.mjs'))) {
  console.log('packages/api not found next to this package; keeping the committed copy.');
  process.exit(0);
}

const routesMod = await import(pathToFileURL(join(apiSrc, 'routes.mjs')).href);
const constants = await import(pathToFileURL(join(apiSrc, 'constants.mjs')).href);
const apiPkg = JSON.parse(await readFile(join(apiSrc, '..', 'package.json'), 'utf8'));

// Keep only what the node uses, without long descriptions.
const slim = Object.fromEntries(
  Object.entries(routesMod.routes).map(([name, r]) => [
    name,
    {
      name,
      path: r.path,
      auth: r.auth,
      pathParams: r.pathParams.map((p) => p.name),
      queryParams: r.queryParams.map((p) => p.name),
      paged: r.paged,
      returns: r.returns,
    },
  ]),
);

const names = Object.keys(slim);
const q = (v) => JSON.stringify(v).replace(/"/g, "'");
const routeLines = names
  .map((n) => {
    const r = slim[n];
    return `\t${n}: {\n\t\tname: '${n}',\n\t\tpath: '${r.path}',\n\t\tauth: ${r.auth},\n\t\tpathParams: ${q(r.pathParams)},\n\t\tqueryParams: ${q(r.queryParams)},\n\t\tpaged: ${r.paged},\n\t\treturns: '${r.returns}',\n\t},`;
  })
  .join('\n');

const content = `// GENERATED by scripts/sync-routes.mjs from ${apiPkg.name} ${apiPkg.version} (API ${routesMod.API_VERSION}).
// Do not edit by hand. The routes live in packages/api, generated from the OpenAPI document.

export type RouteName =
${names.map((n) => `\t| '${n}'`).join('\n')};

export interface Route {
\tname: RouteName;
\tpath: string;
\tauth: boolean;
\tpathParams: string[];
\tqueryParams: string[];
\tpaged: boolean;
\treturns: 'object' | 'array' | 'page';
}

export const ROUTES: Record<RouteName, Route> = {
${routeLines}
};

export const API_VERSION = '${routesMod.API_VERSION}';
export const DEFAULT_BASE_URL = '${routesMod.DEFAULT_BASE_URL}';
export const DEMO_KEY = '${constants.DEMO_KEY}';
export const SAMPLE_ACCOUNT = '${constants.SAMPLE_ACCOUNT}';
export const ENGINE_IDS = ${q([...routesMod.ENGINE_IDS])};
export const ENGINES: Record<string, string> = {
${Object.entries(constants.ENGINES)
  .map(([k, v]) => `\t${k}: '${v}',`)
  .join('\n')}
};
export const EVENT_TYPES = ${q([...constants.EVENT_TYPES])};
export const SIGNATURE_TOLERANCE_SECONDS = ${constants.SIGNATURE_TOLERANCE_SECONDS};
export const WEBHOOK_HEADERS = {
${Object.entries(constants.WEBHOOK_HEADERS)
  .map(([k, v]) => `\t${k}: '${v}',`)
  .join('\n')}
};
`;

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== content) {
    console.error(`Stale: ${target}. Run npm run sync-routes.`);
    process.exit(1);
  }
  console.log('Routes copy is current.');
  process.exit(0);
}

await writeFile(target, content, 'utf8');
console.log(`Wrote ${target} (${names.length} routes).`);
