// GENERATED by scripts/generate-types.mjs from openapi.json (Broadcastwell API 1.0.0).
// Do not edit by hand. Run `npm run generate` in packages/api after updating openapi.json.

/** API version this table was generated from. */
export const API_VERSION = "1.0.0";

/** Default base URL, from the OpenAPI servers list. */
export const DEFAULT_BASE_URL = "https://app.broadcastwell.com/api/v1";

/** Engine ids in the order the API lists them. */
export const ENGINE_IDS = Object.freeze(["chatgpt","claude","perplexity","google_aio","google_ai_mode"]);

/**
 * Every route, keyed by method name (the OpenAPI operationId).
 * Each entry: HTTP method, path template, path and query parameters,
 * whether it pages (pagination.next_cursor) and what `data` holds.
 */
export const routes = Object.freeze({
  "getMe": {
    "name": "getMe",
    "method": "GET",
    "path": "/me",
    "summary": "The key you are using",
    "description": "Who the key belongs to and which accounts it reads.",
    "tag": "Account",
    "auth": true,
    "pathParams": [],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "getMethod": {
    "name": "getMethod",
    "method": "GET",
    "path": "/method",
    "summary": "Method, definitions and limits",
    "description": "The method version, every definition, the five engines, the proof rules and what the numbers do not prove. No key needed.",
    "tag": "Method",
    "auth": false,
    "pathParams": [],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "getAccount": {
    "name": "getAccount",
    "method": "GET",
    "path": "/accounts/{account}",
    "summary": "One account",
    "description": "",
    "tag": "Account",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "listRuns": {
    "name": "listRuns",
    "method": "GET",
    "path": "/accounts/{account}/runs",
    "summary": "Runs",
    "description": "Every measurement the account holds, newest first, with its passes. Scheduled passes carry the figures. Adaptive passes are labelled.",
    "tag": "Runs",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "getRun": {
    "name": "getRun",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}",
    "summary": "One run",
    "description": "",
    "tag": "Runs",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "getRunSummary": {
    "name": "getRunSummary",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/summary",
    "summary": "Run summary",
    "description": "Named and own domain cited rates on scheduled passes, overall, per engine and per question type. Adaptive answers are reported separately.",
    "tag": "Runs",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "listQuestions": {
    "name": "listQuestions",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/questions",
    "summary": "Questions",
    "description": "",
    "tag": "Questions",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "getQuestion": {
    "name": "getQuestion",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/questions/{question}",
    "summary": "One question",
    "description": "Counts per engine, competitors named and who was named instead.",
    "tag": "Questions",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      },
      {
        "name": "question",
        "type": "integer",
        "description": "",
        "minimum": 1,
        "maximum": 35
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "listReceipts": {
    "name": "listReceipts",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/receipts",
    "summary": "Receipts",
    "description": "Observed answers with their verdict and every cited address.",
    "tag": "Receipts",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [
      {
        "name": "question_id",
        "type": "integer",
        "description": "",
        "minimum": 1,
        "maximum": 35
      },
      {
        "name": "engine",
        "type": "string",
        "description": "",
        "enum": [
          "chatgpt",
          "claude",
          "perplexity",
          "google_aio",
          "google_ai_mode"
        ]
      },
      {
        "name": "pass_id",
        "type": "string",
        "description": "",
        "maxLength": 20
      },
      {
        "name": "verdict",
        "type": "string",
        "description": "",
        "enum": [
          "named",
          "not_named",
          "excluded"
        ]
      },
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "getReceipt": {
    "name": "getReceipt",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/receipts/{receipt}",
    "summary": "One receipt",
    "description": "",
    "tag": "Receipts",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      },
      {
        "name": "receipt",
        "type": "string",
        "description": "",
        "maxLength": 300
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "listDisplacement": {
    "name": "listDisplacement",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/displacement",
    "summary": "Named instead",
    "description": "Per question, who was named in answers that did not name the client, including competitors checked and not found.",
    "tag": "Displacement",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "listSources": {
    "name": "listSources",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/sources",
    "summary": "Sources",
    "description": "Every page cited in scheduled answers, with times cited, engines and questions.",
    "tag": "Sources",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "listRunFixes": {
    "name": "listRunFixes",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/fixes",
    "summary": "Fixes for a run",
    "description": "",
    "tag": "Fixes",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "array"
  },
  "compareRuns": {
    "name": "compareRuns",
    "method": "GET",
    "path": "/accounts/{account}/runs/{run}/compare/{other}",
    "summary": "Compare two runs",
    "description": "Named rates on the questions and engines both runs measured. A change is called only where the intervals separate, and never across method versions.",
    "tag": "Runs",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "run",
        "type": "string",
        "description": "A run id from the runs list.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      },
      {
        "name": "other",
        "type": "string",
        "description": "The second run id.",
        "pattern": "^[A-Za-z0-9._:-]{1,200}$"
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  },
  "listFixes": {
    "name": "listFixes",
    "method": "GET",
    "path": "/accounts/{account}/fixes",
    "summary": "Fixes",
    "description": "",
    "tag": "Fixes",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "array"
  },
  "getHistory": {
    "name": "getHistory",
    "method": "GET",
    "path": "/accounts/{account}/history",
    "summary": "History",
    "description": "One point per scheduled run with its interval, for the account, each engine and each question type. Moved is printed only where intervals separate. Method breaks are marked.",
    "tag": "History",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [
      {
        "name": "scope",
        "type": "string",
        "description": "",
        "enum": [
          "account",
          "engine",
          "question_type"
        ]
      }
    ],
    "paged": false,
    "returns": "array"
  },
  "listAlerts": {
    "name": "listAlerts",
    "method": "GET",
    "path": "/accounts/{account}/alerts",
    "summary": "Alerts",
    "description": "Movements between consecutive comparable scheduled runs where the two intervals separate, in either direction.",
    "tag": "Alerts",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [
      {
        "name": "limit",
        "type": "integer",
        "description": "Items per page, 1 to 100. Default 25.",
        "minimum": 1,
        "maximum": 100,
        "default": 25
      },
      {
        "name": "cursor",
        "type": "string",
        "description": "The next_cursor from the previous page.",
        "maxLength": 40
      }
    ],
    "paged": true,
    "returns": "page"
  },
  "listProof": {
    "name": "listProof",
    "method": "GET",
    "path": "/accounts/{account}/proof",
    "summary": "Proof",
    "description": "Controlled lift experiments with the four counts, intervals, the lift in points and the fixed verdict.",
    "tag": "Proof",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "array"
  },
  "getProof": {
    "name": "getProof",
    "method": "GET",
    "path": "/accounts/{account}/proof/{experiment}",
    "summary": "One experiment",
    "description": "",
    "tag": "Proof",
    "auth": true,
    "pathParams": [
      {
        "name": "account",
        "type": "string",
        "description": "me, your account id, or sample for the fictional Kalvenor sample. Any other id answers 404.",
        "maxLength": 200
      },
      {
        "name": "experiment",
        "type": "string",
        "description": "",
        "maxLength": 200
      }
    ],
    "queryParams": [],
    "paged": false,
    "returns": "object"
  }
});
