// GENERATED by scripts/sync-routes.mjs from @broadcastwell/api 0.1.0 (API 1.0.0).
// Do not edit by hand. The routes live in packages/api, generated from the OpenAPI document.

export type RouteName =
	| 'getMe'
	| 'getMethod'
	| 'getAccount'
	| 'listRuns'
	| 'getRun'
	| 'getRunSummary'
	| 'listQuestions'
	| 'getQuestion'
	| 'listReceipts'
	| 'getReceipt'
	| 'listDisplacement'
	| 'listSources'
	| 'listRunFixes'
	| 'compareRuns'
	| 'listFixes'
	| 'getHistory'
	| 'listAlerts'
	| 'listProof'
	| 'getProof';

export interface Route {
	name: RouteName;
	path: string;
	auth: boolean;
	pathParams: string[];
	queryParams: string[];
	paged: boolean;
	returns: 'object' | 'array' | 'page';
}

export const ROUTES: Record<RouteName, Route> = {
	getMe: {
		name: 'getMe',
		path: '/me',
		auth: true,
		pathParams: [],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	getMethod: {
		name: 'getMethod',
		path: '/method',
		auth: false,
		pathParams: [],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	getAccount: {
		name: 'getAccount',
		path: '/accounts/{account}',
		auth: true,
		pathParams: ['account'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	listRuns: {
		name: 'listRuns',
		path: '/accounts/{account}/runs',
		auth: true,
		pathParams: ['account'],
		queryParams: ['limit','cursor'],
		paged: true,
		returns: 'page',
	},
	getRun: {
		name: 'getRun',
		path: '/accounts/{account}/runs/{run}',
		auth: true,
		pathParams: ['account','run'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	getRunSummary: {
		name: 'getRunSummary',
		path: '/accounts/{account}/runs/{run}/summary',
		auth: true,
		pathParams: ['account','run'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	listQuestions: {
		name: 'listQuestions',
		path: '/accounts/{account}/runs/{run}/questions',
		auth: true,
		pathParams: ['account','run'],
		queryParams: ['limit','cursor'],
		paged: true,
		returns: 'page',
	},
	getQuestion: {
		name: 'getQuestion',
		path: '/accounts/{account}/runs/{run}/questions/{question}',
		auth: true,
		pathParams: ['account','run','question'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	listReceipts: {
		name: 'listReceipts',
		path: '/accounts/{account}/runs/{run}/receipts',
		auth: true,
		pathParams: ['account','run'],
		queryParams: ['question_id','engine','pass_id','verdict','limit','cursor'],
		paged: true,
		returns: 'page',
	},
	getReceipt: {
		name: 'getReceipt',
		path: '/accounts/{account}/runs/{run}/receipts/{receipt}',
		auth: true,
		pathParams: ['account','run','receipt'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	listDisplacement: {
		name: 'listDisplacement',
		path: '/accounts/{account}/runs/{run}/displacement',
		auth: true,
		pathParams: ['account','run'],
		queryParams: ['limit','cursor'],
		paged: true,
		returns: 'page',
	},
	listSources: {
		name: 'listSources',
		path: '/accounts/{account}/runs/{run}/sources',
		auth: true,
		pathParams: ['account','run'],
		queryParams: ['limit','cursor'],
		paged: true,
		returns: 'page',
	},
	listRunFixes: {
		name: 'listRunFixes',
		path: '/accounts/{account}/runs/{run}/fixes',
		auth: true,
		pathParams: ['account','run'],
		queryParams: [],
		paged: false,
		returns: 'array',
	},
	compareRuns: {
		name: 'compareRuns',
		path: '/accounts/{account}/runs/{run}/compare/{other}',
		auth: true,
		pathParams: ['account','run','other'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
	listFixes: {
		name: 'listFixes',
		path: '/accounts/{account}/fixes',
		auth: true,
		pathParams: ['account'],
		queryParams: [],
		paged: false,
		returns: 'array',
	},
	getHistory: {
		name: 'getHistory',
		path: '/accounts/{account}/history',
		auth: true,
		pathParams: ['account'],
		queryParams: ['scope'],
		paged: false,
		returns: 'array',
	},
	listAlerts: {
		name: 'listAlerts',
		path: '/accounts/{account}/alerts',
		auth: true,
		pathParams: ['account'],
		queryParams: ['limit','cursor'],
		paged: true,
		returns: 'page',
	},
	listProof: {
		name: 'listProof',
		path: '/accounts/{account}/proof',
		auth: true,
		pathParams: ['account'],
		queryParams: [],
		paged: false,
		returns: 'array',
	},
	getProof: {
		name: 'getProof',
		path: '/accounts/{account}/proof/{experiment}',
		auth: true,
		pathParams: ['account','experiment'],
		queryParams: [],
		paged: false,
		returns: 'object',
	},
};

export const API_VERSION = '1.0.0';
export const DEFAULT_BASE_URL = 'https://app.broadcastwell.com/api/v1';
export const DEMO_KEY = 'bwp_demo_kalvenor_sample';
export const SAMPLE_ACCOUNT = 'sample';
export const ENGINE_IDS = ['chatgpt','claude','perplexity','google_aio','google_ai_mode'];
export const ENGINES: Record<string, string> = {
	chatgpt: 'ChatGPT',
	claude: 'Claude',
	perplexity: 'Perplexity',
	google_aio: 'Google AI Overviews',
	google_ai_mode: 'Google AI Mode',
};
export const EVENT_TYPES = ['run.completed','alert.fired','fix.updated','proof.updated','webhook.test'];
export const SIGNATURE_TOLERANCE_SECONDS = 300;
export const WEBHOOK_HEADERS = {
	signature: 'Broadcastwell-Signature',
	event: 'Broadcastwell-Event',
	eventId: 'Broadcastwell-Event-Id',
	delivery: 'Broadcastwell-Delivery',
};
